var Sqrl = require('squirrelly');
const common = require("./common")
class labelHelp {
    content;
    id;
    htmlTemplate = `
<p id="{{modal.id}}_{{ms.no}}" no="{{ms.no}}" bs-type="label" class="h{{ms.h}} {{if(options.ms.style)}}{{ms.style}}{{/if}}">
<h8>Click the links below to access videos to get you started</h8>
<ul><li><a href="https://youtu.be/AECXhk4-jrc">Getting Started with BlueSky Statistics 10</a></li><li> <a href="https://youtu.be/4WwcFy88Z7A">Overview of the data and variable tab</a></li><li> <a href="https://youtu.be/WMhEVojuE98">Working with empty datasets</a></li><li><a href="https://youtu.be/Cx12PBcjBNc">Running R code in BlueSky Statistics</a></li><li>Coming Soon: Running R markdown generated by BlueSky Statistics</li><li>Coming Soon: Cutting and pasting tables generated in BlueSky Statistics into Office (Word, Excel, PowerPoint)</li></ul>
<h8>Click the links below to access BETA 2 videos</h8>
<ul><li><a href="https://youtu.be/KH2FWSo3IU4">Whats new in BlueSky Statistics Beta 2</a></li><li> <a href="https://youtu.be/jpP9ilu0GBc">Improvements to the R code editor in BlueSky Statistics Beta 2</a></li><li> <a href="https://youtu.be/ypLXqmFp3jY">Reshape / Restructure-Long to Wide</a></li><li><a href="https://youtu.be/5P8g9c5y_U4">Restructure/Reshape data to longer format</a></li></ul>
<h8>Can't find a dialog..</h8>
<p>Click&nbsp;<a href="https://www.blueskystatistics.com/Articles.asp?ID=318"> list of all dialogs</a> to search a complete list of all dialogs in BlueSky Statistics<p><p>
<h8>Technical Support and Feedback</h8><br/>For technical support, please email <a href="mailto:support@blueskystatistics.com">support@blueskystatistics.com</a><p>
<h8>Additional Details</h8></br>
For more details visit <a href="https://www.blueskystatistics.com/">BlueSky Statistics</a>
    `
    constructor(modal, config) {
        this.content = Sqrl.Render(this.htmlTemplate, { modal: modal, ms: config })
    }
    canExecute() {
        return true
    }
    clearContent() { }
}
module.exports.element = labelHelp;